# http://shopify.github.io/ruby-style-guide/rubocop.yml
#
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'db/**/*'
    - 'spec/swagger_helper.rb'
    - 'Gemfile'
    - 'bin/**/*'
    - 'config/**/*'
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 120
  Exclude:
    - 'db/migrate/*.rb'
    - 'db/schema.rb'
Style/GuardClause:
  Enabled: false
Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'
Metrics/AbcSize:
  Enabled: false    
Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'db/schema.rb'
    - 'spec/controllers/*.rb'
    - 'spec/factories/*.rb'
Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'spec/controllers/*.rb'
    - 'spec/factories/*.rb'
    - 'spec/swagger/**/*.rb'
