development: 
  cloud_name: "drcqabzrw"
  api_key: "915239992584483"
  api_secret: "fWAyday3HANHrkxwCG5UPH1lg9g"
  secure: true

production:
  cloud_name: "drcqabzrw"
  api_key: "915239992584483"
  api_secret: "fWAyday3HANHrkxwCG5UPH1lg9g"
  secure: true
